server:
  port: 8085

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/javaee_assignmentb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver